const getChartTheme = (mode = 'light') => {
  if (mode === 'dark') {
    return {
      shell: 'card-elevated overflow-hidden',
      headMain: 'card-head-compact',
      headTitle: 'font-bold tracking-tight text-slate-100 text-base',
      headSub: 'mt-0.5 text-xs text-slate-400',
      inset: 'card-inset p-4 sm:p-5',
      panel: 'card-panel overflow-hidden',
      panelHead: 'card-panel-head',
      panelHeadTitle: 'font-bold tracking-tight text-slate-100 text-sm',
      panelHeadSub: 'mt-0.5 text-xs text-slate-400',
      kpiLegend: 'text-slate-400',
      loadingHead: 'card-head-compact',
      loadingInset: 'card-inset grid gap-4 p-5 sm:grid-cols-2 sm:p-6 lg:grid-cols-2',
      pulseCard: 'border-white/[0.08] bg-white/[0.04] ring-white/[0.04]',
      pulseLine: 'bg-white/10',
      emptyBody: 'card-inset flex flex-col items-center justify-center px-6 py-14 text-center',
      emptyIconWrap: 'border-teal-500/30 bg-teal-500/15 text-teal-300 ring-teal-400/15',
      emptyTitle: 'text-slate-200',
      emptyText: 'text-slate-500',
      gridStroke: '#334155',
      tooltipOuter: {
        borderRadius: 14,
        border: '1px solid rgba(255,255,255,0.12)',
        boxShadow: '0 16px 48px rgba(0,0,0,0.55)',
        padding: '12px 16px',
        background: 'rgba(15, 23, 42, 0.96)',
        color: '#e2e8f0',
      },
      axisTick: {
        fill: '#94a3b8',
        fontSize: 11,
        fontFamily: 'Plus Jakarta Sans, sans-serif',
      },
      tooltipLabel: { fontWeight: 600, marginBottom: 6, color: '#f1f5f9' },
      barCursor: 'rgba(13, 148, 136, 0.12)',
      pieStroke: '#0f172a',
      pieListWrap: 'border-white/[0.08]',
      pieListItem: 'border-white/[0.05]',
      pieTextPri: 'text-slate-200',
      pieTextSec: 'text-slate-500',
      pieMuted: 'text-slate-600',
      lineLegendClass: 'text-slate-400',
    }
  }

  return {
    shell: 'assist-card overflow-hidden shadow-md ring-1 ring-slate-200/70',
    headMain: 'assist-header px-5 py-4 sm:px-6',
    headTitle: 'font-bold tracking-tight text-slate-900 text-base',
    headSub: 'mt-0.5 text-xs text-slate-500',
    inset: 'border-t border-slate-100 bg-slate-50/60 p-4 sm:p-5',
    panel: 'overflow-hidden rounded-2xl border border-slate-200 bg-white',
    panelHead: 'border-b border-slate-100 bg-white px-5 py-3 sm:px-6',
    panelHeadTitle: 'font-bold text-sm tracking-tight text-slate-900',
    panelHeadSub: 'mt-0.5 text-xs text-slate-500',
    kpiLegend: 'text-slate-600',
    loadingHead: 'assist-header px-5 py-4 sm:px-6',
    loadingInset: 'grid gap-4 border-t border-slate-100 bg-slate-50/40 p-5 sm:grid-cols-2 sm:p-6 lg:grid-cols-2',
    pulseCard: 'border-slate-200 bg-white',
    pulseLine: 'bg-slate-200',
    emptyBody:
      'flex flex-col items-center justify-center border-t border-slate-100 bg-slate-50/40 px-6 py-14 text-center',
    emptyIconWrap: 'border-emerald-200 bg-emerald-50 text-emerald-600 ring-emerald-100',
    emptyTitle: 'text-slate-800',
    emptyText: 'text-slate-500',
    gridStroke: '#e2e8f0',
    tooltipOuter: {
      borderRadius: 12,
      border: '1px solid #e2e8f0',
      boxShadow: '0 8px 24px rgba(15, 23, 42, 0.08)',
      padding: '12px 16px',
      background: '#ffffff',
      color: '#0f172a',
    },
    axisTick: {
      fill: '#64748b',
      fontSize: 11,
      fontFamily: 'Plus Jakarta Sans, sans-serif',
    },
    tooltipLabel: { fontWeight: 600, marginBottom: 6, color: '#0f172a' },
    barCursor: 'rgba(16, 185, 129, 0.15)',
    pieStroke: '#ffffff',
    pieListWrap: 'border-slate-200',
    pieListItem: 'border-slate-100',
    pieTextPri: 'text-slate-800',
    pieTextSec: 'text-slate-500',
    pieMuted: 'text-slate-400',
    lineLegendClass: 'text-slate-600',
  }
}

export { getChartTheme }
